version: "3"

services:
  app:
    build: .
    ports:
      - 8001:8080
    environment:
      - ENV=development
      - GRAPHQL_ENDPOINT=http://0.0.0.0:8000
      - TRANSLATIONS_DOCUMENT=dcat_ap_no_validator_web
