version: "3"

services:
  app:
    build: .
    ports:
      - 8001:8080
    environment:
      - ENV=development
      - GRAPHQL_ENDPOINT=http://127.0.0.1:8000
      - VALIDATOR_API_HOST=http://127.0.0.1:8080
      - FDK_REGISTRATION_BASE_URI=https://registrering.fellesdatakatalog.digdir.no/
      - ADMIN_GUI_BASE_URI=https://admin.fellesdatakatalog.digdir.no/
